version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: innosistemas-postgres
    environment:
      POSTGRES_DB: innosistemas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - innosistemas-network

  # Cache Redis (opcional pero recomendado)
  redis:
    image: redis:7-alpine
    container_name: innosistemas-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - innosistemas-network

  # Adminer - Interfaz web para PostgreSQL (opcional, útil para desarrollo)
  adminer:
    image: adminer:latest
    container_name: innosistemas-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - innosistemas-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  innosistemas-network:
    driver: bridge